[package]
name = "atrium-api"
version = "0.15.0"
authors = ["sugyan <sugi1982+github@gmail.com>"]
edition = "2021"
description = "API library for AT Protocol (Bluesky)"
documentation = "https://docs.rs/atrium-api"
readme = "README.md"
repository = "https://github.com/sugyan/atrium"
license = "MIT"
keywords = ["atproto", "bluesky"]

[dependencies]
atrium-xrpc = "0.8.0"
async-trait = "0.1.68"
http = "0.2.9"
serde = { version = "1.0.160", features = ["derive"] }
serde_bytes = "0.11.9"
tokio = { version = "1.33.0", default-features = false, optional = true }
cid = { version = "0.10.1", optional = true }
libipld-core = { version = "0.16.0", optional = true }

[features]
default = ["agent"]
agent = ["tokio/sync"]
dag-cbor = ["cid/serde-codec", "libipld-core/serde-codec"]

[dev-dependencies]
atrium-xrpc-client = "0.2.0"
futures = "0.3.28"
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
serde_ipld_dagcbor = { git = "https://github.com/sugyan/serde_ipld_dagcbor.git", rev = "345b240" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
