[workspace]
publish = false
changelog_update = false

[[package]]
name = "atrium-api"
publish = true
changelog_update = true

[[package]]
name = "atrium-xrpc"
publish = true
changelog_update = true

[[package]]
name = "atrium-xrpc-client"
publish = true
changelog_update = true

[[package]]
name = "atrium-cli"
changelog_update = true
