[workspace]
publish = false
git_release_enable = false
git_tag_enable = false
changelog_update = false

[[package]]
name = "atrium-crypto"
publish = true
git_release_enable = true
git_tag_enable = true
changelog_update = true

[[package]]
name = "atrium-xrpc"
publish = true
git_release_enable = true
git_tag_enable = true
changelog_update = true

[[package]]
name = "atrium-xrpc-client"
publish = true
git_release_enable = true
git_tag_enable = true
changelog_update = true

[[package]]
name = "atrium-api"
publish = true
git_release_enable = true
git_tag_enable = true
changelog_update = true

[[package]]
name = "bsky-sdk"
publish = true
git_release_enable = true
git_tag_enable = true
changelog_update = true

[[package]]
name = "bsky-cli"
publish = true
git_release_enable = true
git_tag_enable = true
changelog_update = true

[changelog]
body = """
## [{{ version | trim_start_matches(pat="v") }}]\
    {%- if release_link -%}\
        ({{ release_link }})\
    {% endif %} \
    - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
    {% for commit in commits %}
        {%- if commit.scope -%}
            - *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}\
                {{ commit.message }} by @{{ commit.author.name }}\
                {%- if commit.links %} \
                    ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%})\
                {% endif %}
        {% else -%}
            - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }} by @{{ commit.author.name }}
        {% endif -%}
    {% endfor -%}
{% endfor %}
"""
commit_parsers = [
    { message = "^feat", group = "added" },
    { message = "^changed", group = "changed" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^fix", group = "fixed" },
    { message = "^security", group = "security" },
    { message = "^remove", group = "removed" },
    { message = "^.*", group = "other" },
]
