[package]
name = "firehose"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atrium-xrpc-server = { path = "../../atrium-xrpc-server" }
atrium-api = { path = "../../atrium-api", default-features = false, features = ["dag-cbor"]}
ciborium = "0.2.1"
futures = "0.3.28"
rs-car = "0.4.1"
tokio = { version = "1.28.1", features = ["full"] }
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
serde_ipld_dagcbor = { git = "https://github.com/sugyan/serde_ipld_dagcbor.git", rev = "345b240" }
