name: API

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build -p atrium-api --verbose
      - name: Run tests
        run: |
          cargo test -p atrium-api --lib
          cargo test -p atrium-api --lib --no-default-features
          cargo test -p atrium-api --lib --all-features
