name: Libs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cargo build -p atrium-libs --verbose
          cargo build -p atrium-libs --verbose --features atproto-data
          cargo build -p atrium-libs --verbose --features common-web
          cargo build -p atrium-libs --verbose --features identity
          cargo build -p atrium-libs --verbose --all-features
      - name: Run tests
        run: |
          cargo test -p atrium-libs --lib
          cargo test -p atrium-libs --lib --all-features
