name: XRPC Client

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build -p atrium-xrpc-client --verbose
      - name: Run tests
        run: |
          cargo test -p atrium-xrpc-client --lib
          cargo test -p atrium-xrpc-client --lib --no-default-features --features=reqwest
          cargo test -p atrium-xrpc-client --lib --no-default-features --features=isahc
          cargo test -p atrium-xrpc-client --lib --no-default-features --features=surf
          cargo test -p atrium-xrpc-client --lib --all-features
      - name: Run doctests
        run: cargo test -p atrium-xrpc-client --doc --all-features
